# -*- coding: utf-8 -*-
"""Etch A Sketch in Python.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1yq-PVaYshmt12JbmIx4z3EDsxvt7f3ok
# How to make the basis of Etch A Sketch in Python 3?
I'm relatively new to Python. So far, I completed the tutorial available on Codecademy and some courses on DataCamp but I thought it would be nice to produce a first product
"""

#importing some modules
import matplotlib.pyplot as plt
import numpy as np

#defining some variables

#pos is the 'real-time' position of my dot
pos = {'x' : 0,
       'y' : 0}

#pos_data is holding all the points that were created.
pos_data = {'x' : [0],
            'y' : [0]}


#function to move
def moveUp():
  global pos
  global pos_data
  pos['y'] = pos['y'] + 1
  pos_data['y'].append(pos['y'])
  pos_data['x'].append(pos['x'])
  
  
def moveDown():
  global pos
  global pos_data
  pos['y'] = pos['y'] - 1
  pos_data['y'].append(pos['y'])
  pos_data['x'].append(pos['x'])
  
def moveLeft():
  global pos
  global pos_data
  pos['x'] = pos['x'] - 1
  pos_data['y'].append(pos['y'])
  pos_data['x'].append(pos['x'])
  
def moveRight():
  global pos
  global pos_data
  pos['x'] = pos['x'] + 1
  pos_data['y'].append(pos['y'])
  pos_data['x'].append(pos['x'])
 
#this function is setting pos to its initial position {'x' : 0, 'y' : 0} 
def initialPosition():
  global pos
  global pos_data
  pos = {'x' : 0,
         'y' : 0}
  pos_data = {'x' :  [0],
              'y' : [0]}
  
#This function returns the drawing space with the current position (pos) of the point
def showMap():
   plt.plot(pos['x'],pos['y'],'bo')
   plt.xticks(np.arange(-10, 11, step=1))
   plt.yticks(np.arange(-10, 11, step=1))
    
#This function is showing the whole trail of your sketch
def showPath():
   plt.plot(pos_data['x'],pos_data['y'])
   plt.xticks(np.arange(-10, 11, step=1))
   plt.yticks(np.arange(-10, 11, step=1))

#Posicion inicial
showMap()

#
print(pos_data)

"""So know we have all the functions to move our position. Let's move!
What would happen if we move:
1 time up, 2 times left and 3 times down ?
"""

moveUp()
moveLeft()
moveLeft()
moveDown()
moveDown()
moveDown()

"""So what's your guess ?"""

showPath()

# Iniciamos desde 0 
initialPosition()

"""So after this first try, let's see how I can make the first letter of my name: a 'C'"""

moveLeft()
moveLeft()
moveLeft()
moveDown()
moveDown()
moveDown()
moveDown()
moveRight()
moveRight()
moveRight()
moveUp()
moveLeft()
moveLeft()
moveUp()
moveUp()
moveRight()
moveRight()
moveUp()

"""And we can plot it as well with our function:"""

showPath()
